apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
        istio.io/dataplane-mode: ambient
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /usr/share/nginx/html/data.json
          subPath: data.json
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: data-volume
        configMap:
          name: backend-data
      - name: config-volume
        configMap:
          name: backend-data
      - name: secret-volume
        secret:
          secretName: db-secret
